// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFjKcYX7JoEsowavtt9mxvBf8BePyFJ7Q',
    appId: '1:114650111407:web:34b70c93641bb6d7fae35a',
    messagingSenderId: '114650111407',
    projectId: 'wv-fb-miner',
    authDomain: 'wv-fb-miner.firebaseapp.com',
    storageBucket: 'wv-fb-miner.appspot.com',
    measurementId: 'G-ZW4936LMRT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAo8Mo3BAVi_Z4iMW8JIF__rBK6zSsQwNM',
    appId: '1:114650111407:android:13b7516428295af7fae35a',
    messagingSenderId: '114650111407',
    projectId: 'wv-fb-miner',
    storageBucket: 'wv-fb-miner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ3fUJ3yuo2NBqZ5PRxvNDWjvA6yBFIw0',
    appId: '1:114650111407:ios:df20a636a0838320fae35a',
    messagingSenderId: '114650111407',
    projectId: 'wv-fb-miner',
    storageBucket: 'wv-fb-miner.appspot.com',
    iosBundleId: 'com.example.fbMinerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ3fUJ3yuo2NBqZ5PRxvNDWjvA6yBFIw0',
    appId: '1:114650111407:ios:df20a636a0838320fae35a',
    messagingSenderId: '114650111407',
    projectId: 'wv-fb-miner',
    storageBucket: 'wv-fb-miner.appspot.com',
    iosBundleId: 'com.example.fbMinerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFjKcYX7JoEsowavtt9mxvBf8BePyFJ7Q',
    appId: '1:114650111407:web:07fc9a2128aecad7fae35a',
    messagingSenderId: '114650111407',
    projectId: 'wv-fb-miner',
    authDomain: 'wv-fb-miner.firebaseapp.com',
    storageBucket: 'wv-fb-miner.appspot.com',
    measurementId: 'G-C4227SBP13',
  );
}
